### ISSUE TITLE
TODO tasks (later)

### ISSUE THREAD

**Issue by ducnx** [proj5/tech2016#38]
- [ ] Follow user
- [ ] Follow topic
- [ ] Add Facebook login
- [x] Add dynamic search bar
- [ ] Add comment in news feed
- [x] Add API to get questions, answers, comments of a user and update in profile
